/**
 * Mock/seed data for development and preview.
 * PT Alkhaleej Travelindo Utama — Hajj & Umrah Travel.
 * Used when the database is empty or for static rendering.
 */

import type { TravelPackage, BlogArticle } from "./types";

export const mockPackages: TravelPackage[] = [
  {
    id: "pkg-haji-mujamalah",
    slug: "haji-mujamalah",
    title: { id: "Haji Mujamalah", en: "Hajj Mujamalah" },
    tagline: { id: "Ibadah haji dengan pelayanan terbaik", en: "Hajj pilgrimage with premium service" },
    heroImage: "/assets/kaabah-masjidil-haram.jpg",
    packageType: "haji_mujamalah",
    aboutText: {
      id: "PT Alkhaleej Travelindo Utama menyediakan paket Haji Mujamalah dengan akomodasi hotel bintang 5 di Makkah dan Madinah, pembimbing ibadah berpengalaman, dan pelayanan 24 jam selama di Tanah Suci. Kami memahami bahwa ibadah haji adalah perjalanan spiritual sekali seumur hidup, oleh karena itu kami hadir dengan layanan terbaik untuk kenyamanan dan kekhusyukan Anda.",
      en: "PT Alkhaleej Travelindo Utama offers Hajj Mujamalah packages with 5-star hotel accommodation in Makkah and Madinah, experienced religious guides, and 24-hour service in the Holy Land.",
    },
    galleryImages: [
      { url: "/assets/kaabah-masjidil-haram.jpg", alt: { id: "Ka'bah di Masjidil Haram Makkah", en: "Kaaba at Masjidil Haram Makkah" }, order: 1 },
      { url: "/assets/kaabah-night.jpg", alt: { id: "Ka'bah di malam hari", en: "Kaaba at night" }, order: 2 },
      { url: "/assets/madinah-masjid-nabawi.jpg", alt: { id: "Masjid Nabawi Madinah", en: "Masjid Nabawi Madinah" }, order: 3 },
      { url: "/assets/madinah-green-dome.jpg", alt: { id: "Kubah Hijau Masjid Nabawi", en: "Green Dome of Masjid Nabawi" }, order: 4 },
      { url: "/assets/haji-tawaf.jpg", alt: { id: "Jamaah haji melakukan tawaf", en: "Pilgrims performing Tawaf" }, order: 5 },
      { url: "/assets/saudi-arabia-makkah.jpg", alt: { id: "Pemandangan Makkah Saudi Arabia", en: "View of Makkah Saudi Arabia" }, order: 6 },
    ],
    tiers: [
      {
        id: "tier-haji-silver",
        name: { id: "Paket Silver", en: "Silver Package" },
        description: { id: "Paket hemat dengan fasilitas standar", en: "Budget-friendly with standard facilities" },
        price: "USD 6.500",
        duration: { id: "40 Hari", en: "40 Days" },
        hotelRating: "3",
        airline: "Garuda Indonesia",
        features: [
          { id: "Hotel bintang 3 di Makkah & Madinah", en: "3-star hotel in Makkah & Madinah" },
          { id: "Transport AC", en: "AC transport" },
          { id: "Makan 3x sehari", en: "3 meals/day" },
          { id: "Pembimbing ibadah berpengalaman", en: "Experienced religious guide" },
          { id: "Manasik haji lengkap", en: "Complete Hajj training" },
          { id: "Handling bandara", en: "Airport handling" },
        ],
        order: 1,
      },
      {
        id: "tier-haji-gold",
        name: { id: "Paket Gold", en: "Gold Package" },
        description: { id: "Paket premium dengan hotel depan Haram", en: "Premium package with hotel facing Haram" },
        price: "USD 9.800",
        duration: { id: "40 Hari", en: "40 Days" },
        hotelRating: "5",
        airline: "Saudi Airlines",
        features: [
          { id: "Hotel bintang 5 depan Masjidil Haram", en: "5-star hotel facing Masjidil Haram" },
          { id: "Hotel bintang 5 dekat Masjid Nabawi", en: "5-star hotel near Masjid Nabawi" },
          { id: "Full board meal", en: "Full board meal" },
          { id: "Pembimbing ibadah bersertifikat", en: "Certified religious guide" },
          { id: "Manasik haji intensif", en: "Intensive Hajj training" },
          { id: "Ziarah Makkah & Madinah khusus", en: "Special Makkah & Madinah ziyarah" },
          { id: "Airport VIP lounge", en: "VIP airport lounge" },
        ],
        order: 2,
      },
      {
        id: "tier-haji-platinum",
        name: { id: "Paket Platinum", en: "Platinum Package" },
        description: { id: "Paket VIP dengan layanan maksimal", en: "VIP package with maximum service" },
        price: "USD 14.500",
        duration: { id: "40 Hari", en: "40 Days" },
        hotelRating: "5",
        airline: "First Class",
        features: [
          { id: "Suite hotel bintang 5 depan Haram", en: "5-star suite hotel facing Haram" },
          { id: "Private transport", en: "Private transport" },
          { id: "Full board meal premium", en: "Premium full board meal" },
          { id: "Pembimbing ibadah VIP 1-on-1", en: "VIP 1-on-1 religious guide" },
          { id: "Ziarah eksklusif Arafah, Mina, Muzdalifah", en: "Exclusive Arafah, Mina, Muzdalifah ziyarah" },
          { id: "Laundry service", en: "Laundry service" },
          { id: "Medical support 24 jam", en: "24-hour medical support" },
          { id: "Sim card Saudi Arabia", en: "Saudi Arabia SIM card" },
        ],
        order: 3,
      },
    ],
    departureSchedules: [
      { id: "sched-1", departureDate: "2026-06-01", returnDate: "2026-07-10", departureCity: { id: "Jakarta", en: "Jakarta" }, availableSeats: 50, status: "open", notes: "Keberangkatan via Soekarno-Hatta", order: 1 },
      { id: "sched-2", departureDate: "2026-06-05", returnDate: "2026-07-14", departureCity: { id: "Surabaya", en: "Surabaya" }, availableSeats: 30, status: "open", notes: "Keberangkatan via Juanda", order: 2 },
    ],
    testimonials: [
      { id: "testi-1", author: "Hj. Fatimah", content: { id: "Alhamdulillah, ibadah haji saya sangat nyaman bersama Alkhaleej. Hotel dekat Haram, makanan enak, dan pembimbing sabar membimbing kami.", en: "Alhamdulillah, my Hajj was very comfortable with Alkhaleej." }, rating: 5, originCity: "Jakarta", year: "2025" },
      { id: "testi-2", author: "H. Ahmad Fauzi", content: { id: "Pelayanan luar biasa. Dari manasik hingga pulang, semuanya terkoordinasi dengan baik. Hotel bintang 5 depan Haram, tinggal jalan kaki.", en: "Exceptional service. Everything was well-coordinated." }, rating: 5, originCity: "Surabaya", year: "2025" },
      { id: "testi-3", author: "Hj. Siti Aminah", content: { id: "Pertama kali haji dan langsung fall in love dengan pelayanan Alkhaleej. Pembimbing sangat detail menjelaskan setiap ritual ibadah.", en: "First time Hajj and I fell in love with Alkhaleej's service." }, rating: 5, originCity: "Bandung", year: "2025" },
    ],
    faqEntries: [
      { id: "faq-1", question: { id: "Berapa lama proses pendaftaran Haji Mujamalah?", en: "How long is the Hajj Mujamalah registration process?" }, answer: { id: "Proses pendaftaran biasanya memakan waktu 1-3 bulan sebelum keberangkatan. Kami akan membantu semua proses administrasi.", en: "Registration usually takes 1-3 months before departure. We will assist with all administrative processes." }, order: 1 },
      { id: "faq-2", question: { id: "Apakah ada manasik haji sebelum berangkat?", en: "Is there Hajj training before departure?" }, answer: { id: "Ya, kami menyediakan manasik haji intensif beberapa kali sebelum keberangkatan, dipandu oleh ustadz berpengalaman.", en: "Yes, we provide intensive Hajj training sessions before departure, guided by experienced religious teachers." }, order: 2 },
      { id: "faq-3", question: { id: "Bagaimana sistem akomodasi hotelnya?", en: "How does the hotel accommodation work?" }, answer: { id: "Hotel bintang 3-5 tergantung paket yang dipilih. Lokasi strategis, dekat dengan Masjidil Haram dan Masjid Nabawi.", en: "3-5 star hotels depending on the package. Strategic location, close to Masjidil Haram and Masjid Nabawi." }, order: 3 },
    ],
    whatsappNumber: "966563317582",
    status: "published",
    createdAt: "2026-01-15 10:00:00",
    updatedAt: "2026-01-15 10:00:00",
  },
  {
    id: "pkg-umrah",
    slug: "umrah",
    title: { id: "Paket Umrah", en: "Umrah Package" },
    tagline: { id: "Umrah nyaman dan berkesan", en: "Comfortable and memorable Umrah" },
    heroImage: "/assets/madinah-masjid-nabawi.jpg",
    packageType: "umrah",
    aboutText: {
      id: "Paket Umrah dengan berbagai pilihan hotel di depan Masjidil Haram Makkah dan Masjid Nabawi Madinah. Dilengkapi dengan pembimbing ibadah berpengalaman, ziarah menyeluruh ke tempat-tempat bersejarah, dan handling bandara. Wujudkan niat ibadah umrah Anda bersama kami.",
      en: "Umrah packages with various hotel options near Masjidil Haram and Masjid Nabawi. Complete with experienced religious guides and airport handling.",
    },
    galleryImages: [
      { url: "/assets/madinah-masjid-nabawi.jpg", alt: { id: "Masjid Nabawi Madinah", en: "Masjid Nabawi Madinah" }, order: 1 },
      { url: "/assets/kaabah-masjidil-haram.jpg", alt: { id: "Ka'bah Masjidil Haram Makkah", en: "Kaaba Masjidil Haram Makkah" }, order: 2 },
      { url: "/assets/umrah-ihram.jpg", alt: { id: "Jamaah umrah berihram", en: "Pilgrims in Ihram" }, order: 3 },
      { url: "/assets/madinah-green-dome.jpg", alt: { id: "Kubah Hijau Rasulullah SAW", en: "The Green Dome of Prophet Muhammad SAW" }, order: 4 },
      { url: "/assets/haji-tawaf.jpg", alt: { id: "Tawaf di Ka'bah", en: "Tawaf around Kaaba" }, order: 5 },
    ],
    tiers: [
      {
        id: "tier-umrah-silver",
        name: { id: "Paket Silver 9 Hari", en: "Silver Package 9 Days" },
        description: { id: "Umrah hemat 9 hari", en: "Budget Umrah 9 days" },
        price: "USD 2.200",
        duration: { id: "9 Hari", en: "9 Days" },
        hotelRating: "3",
        airline: "Lion Air",
        features: [
          { id: "Hotel bintang 3 di Makkah & Madinah", en: "3-star hotel in Makkah & Madinah" },
          { id: "Makan 3x sehari", en: "3 meals/day" },
          { id: "Pembimbing ibadah berpengalaman", en: "Experienced religious guide" },
          { id: "Ziarah Makkah & Madinah", en: "Makkah & Madinah ziyarah" },
          { id: "Handling bandara", en: "Airport handling" },
        ],
        order: 1,
      },
      {
        id: "tier-umrah-gold",
        name: { id: "Paket Gold 9 Hari", en: "Gold Package 9 Days" },
        description: { id: "Umrah premium dengan hotel depan Haram & Nabawi", en: "Premium Umrah with hotel facing Haram & Nabawi" },
        price: "USD 3.500",
        duration: { id: "9 Hari", en: "9 Days" },
        hotelRating: "5",
        airline: "Garuda Indonesia",
        features: [
          { id: "Hotel bintang 5 depan Masjidil Haram", en: "5-star hotel facing Masjidil Haram" },
          { id: "Hotel bintang 5 dekat Masjid Nabawi", en: "5-star hotel near Masjid Nabawi" },
          { id: "Full board meal", en: "Full board meal" },
          { id: "Pembimbing ibadah bersertifikat", en: "Certified religious guide" },
          { id: "Ziarah menyeluruh Makkah & Madinah", en: "Comprehensive Makkah & Madinah ziyarah" },
          { id: "Welcome package", en: "Welcome package" },
        ],
        order: 2,
      },
      {
        id: "tier-umrah-platinum",
        name: { id: "Paket Platinum 12 Hari", en: "Platinum Package 12 Days" },
        description: { id: "Umrah premium extended dengan lebih banyak waktu ibadah", en: "Premium extended Umrah with more worship time" },
        price: "USD 5.200",
        duration: { id: "12 Hari", en: "12 Days" },
        hotelRating: "5",
        airline: "Garuda Indonesia",
        features: [
          { id: "Suite hotel bintang 5 depan Haram", en: "5-star suite hotel facing Haram" },
          { id: "Suite hotel bintang 5 depan Nabawi", en: "5-star suite hotel facing Nabawi" },
          { id: "Full board meal premium", en: "Premium full board meal" },
          { id: "Pembimbing ibadah VIP", en: "VIP religious guide" },
          { id: "Ziarah eksklusif Jabal Nur, Jabal Uhud, dll", en: "Exclusive Jabal Nur, Jabal Uhud ziyarah" },
          { id: "Private transport", en: "Private transport" },
          { id: "Medical support", en: "Medical support" },
        ],
        order: 3,
      },
    ],
    departureSchedules: [
      { id: "sched-3", departureDate: "2026-07-15", returnDate: "2026-07-23", departureCity: { id: "Jakarta", en: "Jakarta" }, availableSeats: 45, status: "open", notes: "Keberangkatan via Soekarno-Hatta", order: 1 },
      { id: "sched-4", departureDate: "2026-08-01", returnDate: "2026-08-09", departureCity: { id: "Surabaya", en: "Surabaya" }, availableSeats: 35, status: "open", notes: "Keberangkatan via Juanda", order: 2 },
      { id: "sched-5", departureDate: "2026-09-01", returnDate: "2026-09-09", departureCity: { id: "Bandung", en: "Bandung" }, availableSeats: 30, status: "open", notes: "Keberangkatan via Husein Sastranegara", order: 3 },
      { id: "sched-6", departureDate: "2026-10-15", returnDate: "2026-10-23", departureCity: { id: "Jakarta", en: "Jakarta" }, availableSeats: 40, status: "open", notes: "Keberangkatan via Soekarno-Hatta", order: 4 },
    ],
    testimonials: [
      { id: "testi-4", author: "Siti Rahmawati", content: { id: "Umrah pertama saya dan sangat berkesan. Hotel bintang 5 depan Haram, tinggal jalan kaki. Pembimbing sangat sabar membimbing kami.", en: "My first Umrah and it was memorable. 5-star hotel right in front of Haram." }, rating: 5, originCity: "Bandung", year: "2025" },
      { id: "testi-5", author: "H. Abdul Rahman", content: { id: "Sudah 3 kali umrah bersama Alkhaleej dan selalu puas. Pelayanan konsisten, hotel terbaik, dan pembimbing sangat kompeten.", en: "3rd Umrah with Alkhaleej and always satisfied." }, rating: 5, originCity: "Jakarta", year: "2025" },
    ],
    faqEntries: [
      { id: "faq-4", question: { id: "Apakah ada pembimbing ibadah?", en: "Is there a religious guide?" }, answer: { id: "Ya, setiap rombongan didampingi pembimbing ibadah berpengalaman dan bersertifikat dari Kementerian Agama.", en: "Yes, every group is accompanied by an experienced and certified religious guide." }, order: 1 },
      { id: "faq-5", question: { id: "Berapa lama proses visa Umrah?", en: "How long does the Umrah visa process take?" }, answer: { id: "Proses visa umrah biasanya memakan waktu 2-4 minggu. Kami akan mengurus semua kebutuhan visa Anda.", en: "The Umrah visa process usually takes 2-4 weeks. We will handle all your visa needs." }, order: 2 },
    ],
    whatsappNumber: "966563317582",
    status: "published",
    createdAt: "2026-02-01 10:00:00",
    updatedAt: "2026-02-01 10:00:00",
  },
];

export const mockBlogArticles: BlogArticle[] = [
  {
    id: "blog-1-id",
    slug: "persiapan-haji-pertama-kali",
    title: "Persiapan Haji Pertama Kali: Panduan Lengkap",
    excerpt: "Semua yang perlu Anda ketahui sebelum berangkat haji untuk pertama kali.",
    content: "<h2>Persiapan Fisik</h2><p>Sebelum berangkat haji, pastikan kondisi fisik Anda prima. Latihan jalan kaki minimal 3-5 km per hari minimal 1 bulan sebelum keberangkatan.</p><h2>Persiapan Dokumen</h2><p>Siapkan paspor dengan masa berlaku minimal 6 bulan, KTP, KK, surat keterangan sehat dari dokter, dan bukti setor tabungan haji.</p><h2>Persiapan Mental & Spiritual</h2><p>Perbanyak istighfar, taubat, dan niat yang ikhlas. Ikuti manasik haji yang disediakan oleh travel agent untuk memahami setiap ritual ibadah.</p>",
    language: "id",
    thumbnailUrl: "/assets/kaabah-masjidil-haram.jpg",
    metaDescription: "Panduan lengkap persiapan haji pertama kali dari Alkhaleej Travelindo Utama",
    ogImage: "/assets/kaabah-masjidil-haram.jpg",
    relatedPackageIds: ["pkg-haji-mujamalah"],
    pairedArticleId: null,
    status: "published",
    publishedAt: "2026-01-20 10:00:00",
    createdAt: "2026-01-20 10:00:00",
    updatedAt: "2026-01-20 10:00:00",
  },
  {
    id: "blog-2-id",
    slug: "keutamaan-umrah-di-bulan-rajab",
    title: "Keutamaan Umrah di Bulan Rajab",
    excerpt: "Mengapa bulan Rajab menjadi waktu istimewa untuk menunaikan umrah.",
    content: "<h2>Keistimewaan Bulan Rajab</h2><p>Bulan Rajab termasuk bulan haram yang diagungkan dalam Islam. Banyak ulama menganjurkan untuk memperbanyak ibadah di bulan ini, termasuk menunaikan umrah.</p><h2>Persiapan Umrah di Bulan Rajab</h2><p>Pastikan pendaftaran dilakukan jauh-jauh hari karena kuota umrah di bulan Rajab biasanya lebih terbatas.</p>",
    language: "id",
    thumbnailUrl: "/assets/madinah-masjid-nabawi.jpg",
    metaDescription: "Keutamaan umrah di bulan Rajab dan persiapannya",
    ogImage: "/assets/madinah-masjid-nabawi.jpg",
    relatedPackageIds: ["pkg-umrah"],
    pairedArticleId: null,
    status: "published",
    publishedAt: "2026-02-01 10:00:00",
    createdAt: "2026-02-01 10:00:00",
    updatedAt: "2026-02-01 10:00:00",
  },
  {
    id: "blog-3-id",
    slug: "tips-sehat-selama-di-tanah-suci",
    title: "Tips Sehat Selama di Tanah Suci",
    excerpt: "Menjaga kesehatan selama ibadah haji dan umrah agar ibadah lebih khusyuk.",
    content: "<h2>Persiapan Fisik</h2><p>Lakukan olahraga rutin jalan kaki minimal 3 km per hari sebelum berangkat. Cuaca di Saudi Arabia sangat panas, jadi pastikan tubuh Anda terbiasa.</p><h2>Makan dan Minum</h2><p>Selalu bawa air minum dan jangan lupa minum minimal 2 liter per hari. Makan makanan yang bergizi dan hindari makanan yang tidak hygienis.</p><h2>Obat-obatan</h2><p>Bawa obat-obatan pribadi dan P3K sederhana. Jangan lupa sunblock dan vitamin.</p>",
    language: "id",
    thumbnailUrl: "/assets/umrah-ihram.jpg",
    metaDescription: "Tips menjaga kesehatan selama ibadah haji dan umrah",
    ogImage: "/assets/umrah-ihram.jpg",
    relatedPackageIds: ["pkg-haji-mujamalah", "pkg-umrah"],
    pairedArticleId: null,
    status: "published",
    publishedAt: "2026-03-01 10:00:00",
    createdAt: "2026-03-01 10:00:00",
    updatedAt: "2026-03-01 10:00:00",
  },
];

/**
 * Format number as Indonesian Rupiah.
 */
export function formatIDR(n: number): string {
  return new Intl.NumberFormat("id-ID", {
    style: "currency",
    currency: "IDR",
    maximumFractionDigits: 0,
  }).format(n);
}
