import type { SiteSettings } from "@/lib/db/site-settings";

export const SiteSettingsDefaults: SiteSettings = {
  brandNameId: "Alkhaleej Travelindo Utama",
  brandNameEn: "Alkhaleej Travelindo Utama",
  taglineId: "Partner perjalanan Haji & Umrah terpercaya",
  taglineEn: "Your trusted Hajj & Umrah travel partner",
  logoUrl: "/logo.png",
  faviconUrl: null,
  primaryWhatsappNumber: "966563317582",
  supportEmail: "fifi@travelindo-utama.com",
  address: "Jl. Bangka Raya RT.011/011, Kec. Mampang Prapatan, Jakarta Selatan, DKI Jakarta 12720",
  socialInstagramUrl: null,
  socialYoutubeUrl: null,
  socialFacebookUrl: null,
  socialTiktokUrl: null,
  heroImageUrl: "/assets/hero-haji.jpg",
  heroTitleId: "Wujudkan Perjalanan Suci Anda Bersama Kami",
  heroTitleEn: "Fulfill Your Sacred Journey With Us",
  heroSubtitleId: "PT Alkhaleej Travelindo Utama — mitra perjalanan Haji & Umrah terpercaya dengan pelayanan premium dan pembimbing ibadah berpengalaman.",
  heroSubtitleEn: "PT Alkhaleej Travelindo Utama — your trusted Hajj & Umrah travel partner with premium service and experienced religious guides.",
  heroCtaTextId: "Lihat Paket",
  heroCtaTextEn: "View Packages",
  packagesCountOverride: null,
  packagesCountAuto: true,
  happyJamaahCount: 0,
  averageRating: 0,
  yearsExperience: 0,
  defaultOgImage: null,
  defaultMetaDescriptionTemplateId: "PT Alkhaleej Travelindo Utama — penyedia paket Haji, Umrah, dan wisata Muslim terpercaya.",
  defaultMetaDescriptionTemplateEn: "PT Alkhaleej Travelindo Utama — trusted provider of Hajj, Umrah, and Muslim tour packages.",
  copyrightText: "© PT Alkhaleej Travelindo Utama. Semua hak dilindungi.",
  footerTaglineId: null,
  footerTaglineEn: null,
  gtmContainerId: null,
  ga4MeasurementId: null,
  customHeadHtml: null,
  updatedAt: "",
};
